version: '3'

services:
  worker:
    image: workerpubg
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    links:
      - mongo
    build:
      context: ./
      dockerfile: ./Worker-Dockerfile
  publicapi:
    image: publicapipubg
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:80"
    links:
      - worker
      - redis
    build:
      context: ./
      dockerfile: ./PubgApi-Dockerfile
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
    - ./data:/data/db
